# Generated by Django 3.2.16 on 2023-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
