# Generated by Django 3.2.16 on 2023-01-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoo', '0003_auto_20230114_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='patient', max_length=20),
        ),
    ]
